apiVersion: v1
data:
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, projects, *, *, allow
    p, role:org-admin, roles, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    g, nikolas.philips@gmail.com, role:org-admin
    g, joachim.prinzbach@gmail.com, role:org-admin

    p, role:baloise-incubator, applications, get, baloise-incubator/*, allow
    p, role:baloise-incubator, applications, sync, baloise-incubator/*, allow
    p, role:baloise-incubator, projects, get, baloise-incubator, allow
    p, role:baloise-incubator, clusters, get, *, allow
    p, role:baloise-incubator, repositories, get, *, allow
    g, baloise-incubator:, role:baloise-incubator


#  policy.csv: |
#    p, role:org-admin, applications, *, */*, allow
#    p, role:org-admin, clusters, get, *, allow
#    p, role:org-admin, repositories, get, *, allow
#    p, role:org-admin, repositories, create, *, allow
#    p, role:org-admin, repositories, update, *, allow
#    p, role:org-admin, repositories, delete, *, allow
#    g, nikio:wheel, role:org-admin
#    g, admin@nikio.io, role:org-admin

  policy.default: 'role:baloise-incubator'
  scopes: '[cognito:groups, email]'
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
