apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: 'role:readonly'
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, projects, *, *, allow
    p, role:org-admin, roles, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    g, baloise-incubator:argocd-administrators, role:org-admin

    p, role:baloise-incubator, applications, get, baloise-incubator/*, allow
    p, role:baloise-incubator, applications, sync, baloise-incubator/*, allow
    p, role:baloise-incubator, projects, get, baloise-incubator, allow
    p, role:baloise-incubator, clusters, get, *, allow
    p, role:baloise-incubator, repositories, get, *, allow
    g, baloise-incubator:, role:org-admin

    p, role:readonly, applications, get, */*, allow
    p, role:readonly, certificates, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow


