apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 4
  template:
    spec:
      containers:
        - image: 'harbor.baloise.dev/library/argocd:latest'
          name: argocd-repo-server