apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 2
#  template:
#    spec:
#      containers:
#        - image: 'niiku/argocd:latest'
#          name: argocd-repo-server
