apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, projects, *, *, allow
    p, role:org-admin, roles, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    g, nikolas.philips@gmail.com, role:org-admin
    g, joachim.prinzbach@gmail.com, role:org-admin

    p, role:baloise-incubator, applications, get, baloise-incubator/*, allow
    p, role:baloise-incubator, applications, sync, baloise-incubator/*, allow
    p, role:baloise-incubator, projects, get, baloise-incubator, allow
    p, role:baloise-incubator, clusters, get, *, allow
    p, role:baloise-incubator, repositories, get, *, allow
    g, baloise-incubator:, role:baloise-incubator

  policy.default: 'role:readonly'
  scopes: '[cognito:groups, email]'

