---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitoringdashboards.monitoring.kiali.io
  labels:
    app: kiali
    version: v1.0.0
spec:
  group: monitoring.kiali.io
  names:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kialis.kiali.io
  labels:
    app: kiali-operator
    version: v1.0.0
spec:
  group: kiali.io
  names:
    kind: Kiali
    listKind: KialiList
    plural: kialis
    singular: kiali
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    version: v1.0.0
---
# NOTE: Changes to this file must be reflected in the OperatorHub.io CSV file
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    version: v1.0.0
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - pods
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - get
      - list
      - patch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
    verbs:
      - create
      - get
  - apiGroups: ["apps"]
    resourceNames:
      - kiali-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups: ["kiali.io"]
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["oauth.openshift.io"]
    resources:
      - oauthclients
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["monitoring.kiali.io"]
    resources:
      - monitoringdashboards
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # The permissions below are for Kiali itself; operator needs these so it can escalate when creating Kiali's roles
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - pods
      - pods/log
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions", "apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["config.istio.io"]
    resources:
      - adapters
      - apikeys
      - bypasses
      - authorizations
      - checknothings
      - circonuses
      - cloudwatches
      - deniers
      - dogstatsds
      - edges
      - fluentds
      - handlers
      - instances
      - kubernetesenvs
      - kuberneteses
      - listcheckers
      - listentries
      - logentries
      - memquotas
      - metrics
      - noops
      - opas
      - prometheuses
      - quotas
      - quotaspecbindings
      - quotaspecs
      - rbacs
      - redisquotas
      - reportnothings
      - rules
      - signalfxs
      - solarwindses
      - stackdrivers
      - statsds
      - stdios
      - templates
      - tracespans
      - zipkins
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups: ["networking.istio.io"]
    resources:
      - destinationrules
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups: ["authentication.istio.io"]
    resources:
      - meshpolicies
      - policies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups: ["rbac.istio.io"]
    resources:
      - clusterrbacconfigs
      - rbacconfigs
      - servicerolebindings
      - serviceroles
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups: ["apps.openshift.io"]
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["project.openshift.io"]
    resources:
      - projects
    verbs:
      - get
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs:
      - get
  - apiGroups: ["monitoring.kiali.io"]
    resources:
      - monitoringdashboards
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    version: v1.0.0
subjects:
  - kind: ServiceAccount
    name: kiali-operator
    namespace: kiali-operator
roleRef:
  kind: ClusterRole
  name: kiali-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-operator
  labels:
    app: kiali-operator
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali-operator
      version: v1.0.0
  template:
    metadata:
      name: kiali-operator
      labels:
        app: kiali-operator
        version: v1.0.0
    spec:
      serviceAccountName: kiali-operator
      containers:
        - name: ansible
          command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
          image: quay.io/kiali/kiali-operator:v1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
        - name: operator
          image: quay.io/kiali/kiali-operator:v1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kiali-operator"
      volumes:
        - name: runner
          emptyDir: {}
