apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: chartmuseum
  namespace: chartmuseum
spec:
  encryptedData:
    BASIC_AUTH_PASS: AgB5UP6+NFWzWXAivCbJi9X0llwcudDYqNwKKY85NFuCigqK6GnkN3lPp1gPkl/RMI6812pKhGZEpWJZBmCjswa5fQUwS+w3Kuf3uonFcr7TygG8QxNbP5Az6xQ/Ng9lR+K0Ynle59B9kDpjDnEiFTdd16SdF7m06TtKNGmhNYN6KQYX0D+x8IVTYJLS6/p+ix+AdS2NVhW0sZff8gCqTiBc9jpFxlRVTUBa1jG4qgHtmpLuzm84R4Buu/x6m91YhkQikX075nW5ABl/V0x4kRF8gq7QX/tWz6lrumwTDu66z0/nnaNV4ZR1Nu8RGt9gwGeQAi8BDccWBJ7gLSku2q1Eb5Z3aJnCo/fbWlo84oiZqRAk5MQ1hKHeCtSGVBOOtzBVY+/edzt08MfSt53ML4wxiMS9Qd9MdlJqqmZBuaI6JGM+4mfjhZc0K3btJuW5gcT1sdAlHzk/ZAlw7Vcq9LGgjeCK3BSGAGHwzW9z//THNevo/igAyHWN84YGUUGLmc9RubWgFf9R7IEuP6fxdju7G1ycH3wju8hhTLhDXwAuo4JlgnhpXfTfuDz6juhTnKYNjCgVbVUvjaID8+QhgmAhxEfGMM0C7czmeTXStW7HgMclWolcIBVWNJTtlgmaOe3TJd7RoBYM82gQMqpRmVldXHZJwXJJFCZRebhgqJw9/LprukFJCBIQOkbnVe8iAucWOJSfJjB4EXCH9okAY1Dj
    BASIC_AUTH_USER: AgBMxvSj4Tfc+LLlR+AQZrx6onST6kORFKCKB3vCLpjyCf9alWkGcXSFz0rd3SH6wyQkNFdmcQfx0l09Ph/hQC4B4tqRoXyfmB4BFGcdZ87981VdyYj2xsUPoRQQxDemo71qPioIMDoZE7r+yOkDYyLF0ZS43di5wyXZM5GAEOu2978K9/y+Ia1ZO+1EgvDxJtRcvaPJl3kTbkMs6EUJ1miiAc9fiWYz1p7vRhvDnjK5QGLBJJOA820FMeVA7z7jq9hfY/YJUQveW+rXWv1bzck4oYpJEtibA/QRUrzIjz5PlNeYZvWCwy2CeNvLctT3mcvCMd6s5Tahb1+Uo+jq7FVvI341Ub+SZXPtms4LlcbAO30w+SHMRczouIXjgWaXpcYS12o3eUD5ct/Flc5HmQpK7I6zkEgni93B3oum4ODqqjCFiUKmbcNlKnVwILb5e3fb8mGMZGvdTlauqvgePCQeqi550j9Nn6OVCw3DmtxEQR3wZwbDohG90p/Ps1bxnx+7V6FAyLCZvg8LYpXMpc52xa1XhvYYkgBiOT0Cu45HMySsOV9zOlLMrtqcVF7pOJwKVPiYu467YthsY0BpSgE2ElBKIvU/FY/EkWcOvGpWTjGcPev+GZAAUhglyOmH78zpg5x4s6YCQ/xws7Y2tY5iOW8YFUtzdfzDa3985Atqp2qdIWi0Rb9d/13gEmQaSzf+mAItJslKZyJm/Q==
  template:
    metadata:
      creationTimestamp: null
      name: chartmuseum
      namespace: chartmuseum
status: {}

