{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels: {{ include "harbor.labels" . | nindent 4 }}
  name: {{ template "harbor.fullname" . }}
spec:
  host: {{ .Values.route.url }}
  path: /
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.termination }}
  to:
    kind: Service
    name: {{ .Values.harbor.service.clusterIP.name }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router
{{- end}}