---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: leubedane
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/leubedane/registration-deployment.git
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc  
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: niiku
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/niiku/deployment-config.git
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: baloise-incubator
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/baloise-incubator/argonaut-deployment-configuration
  destinations:
    - namespace: 'argonaut'
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: table-tennis-tournament
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/table-tennis-tournament/deployment-configuration
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

