{{- range .Values.projects -}}
{{- if or ((kindIs "invalid" .enabled)) .enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
{{- if .clusterResourceWhitelist }}
  clusterResourceWhitelist:
{{- toYaml .clusterResourceWhitelist | nindent 4 -}}
{{ end }}
{{ end }}
{{- end }}