{{- range .Values.applications -}}
{{- $nodeSelector := "node-role.kubernetes.io/compute=true" -}}
{{- if not (kindIs "invalid" .nodeSelector) -}}
{{- $nodeSelector = .nodeSelector -}}
{{- end -}}
{{- if not .noNamespaceCreation -}}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: {{ default "" .description | quote }}
    openshift.io/display-name: {{ default "" .displayName | quote }}
    openshift.io/requester: {{ default "" $.Values.requestor | quote }}
    openshift.io/node-selector: {{ $nodeSelector | quote }}
  name: {{ default .name .namespace | quote }}
{{- end }}
{{- if .admins }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: {{ default .name .namespace | quote }}
roleRef:
  name: admin
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range .admins }}
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: {{ . }}
{{ end }}
{{ end }}
{{ end }}