apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: istio-admin
rules:
- apiGroups:
  - config.istio.io
  - networking.istio.io
  - authentication.istio.io
  - rbac.istio.io
  - authentication.maistra.io
  - rbac.maistra.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
