apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: security
    app.kubernetes.io/component: security
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: security
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: '1'
    chart: security
    heritage: Tiller
    maistra-version: 1.0.0
    maistra.io/owner: istio-system
    release: istio
  name: istio-citadel-istio-system
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - watch
      - list
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
      - services
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshmemberrolls
    verbs:
      - get
      - list
      - watch