apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    app: pilot
    app.kubernetes.io/component: pilot
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: pilot
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: "1"
    chart: pilot
    heritage: Tiller
    maistra-version: 1.0.0
    maistra.io/owner: istio-system
    release: istio
  name: istio-pilot-istio-system
rules:
- apiGroups:
  - config.istio.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.istio.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - authentication.istio.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - maistra.io
  attributeRestrictions: null
  resources:
  - servicemeshmemberrolls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - '*'
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - namespaces
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.maistra.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.maistra.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
