apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    app: security
    app.kubernetes.io/component: security
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: security
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: "1"
    chart: security
    heritage: Tiller
    maistra-version: 1.0.0
    maistra.io/owner: istio-system
    release: istio
  name: istio-citadel-istio-system
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - maistra.io
  attributeRestrictions: null
  resources:
  - servicemeshmemberrolls
  verbs:
  - get
  - list
  - watch
