apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    app: mixer
    app.kubernetes.io/component: mixer
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: mixer
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: "1"
    chart: mixer
    heritage: Tiller
    maistra-version: 1.0.0
    maistra.io/owner: istio-system
    release: istio
  name: istio-mixer-istio-system
rules:
- apiGroups:
  - config.istio.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - maistra.io
  attributeRestrictions: null
  resources:
  - servicemeshmemberrolls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - endpoints
  - namespaces
  - pods
  - replicationcontrollers
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - apps
  attributeRestrictions: null
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
