apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: "1"
  name: prometheus-istio-system
rules:
- apiGroups:
  - maistra.io
  attributeRestrictions: null
  resources:
  - servicemeshmemberrolls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  verbs:
  - get
- apiGroups: null
  attributeRestrictions: null
  nonResourceURLs:
  - /metrics
  resources: []
  verbs:
  - get
