server: https://kubernetes.default.svc
defaultProject: default
requestor: admin@baloise.dev
projects:
  - name: leubedane
  - name: niiku
  - name: baloise-incubator
  - name: table-tennis-tournament
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:
  - name: apps
    namespace: argocd
    noNamespaceCreation: true
    templateEngine: helm
  - name: argocd
    nodeSelector: ""
  - name: eclipse-che
  - name: guacamole
    templateEngine: helm
  - name: harbor
    templateEngine: helm
  - name: katafygio
    enabled: false
    templateEngine: helm
  - name: monocular
    enabled: false
    templateEngine: helm
  - name: openshift-acme
  - name: rook-ceph
    nodeSelector: ""
  - name: sealed-secrets
    templateEngine: helm
  - name: strimzi
    templateEngine: helm
  - name: chartmuseum
    templateEngine: helm
  - name: keycloak
    templateEngine: helm
  - name: argonaut
    project: baloise-incubator
    templateEngine: helm
    repoURL: https://github.com/baloise-incubator/argonaut-deployment-configuration
  - name: tournament-manager
    project: leubedane
    admins:
      - leubedane
    templateEngine: helm
    repoURL: https://github.com/leubedane/registration-deployment.git
  - name: tournament-registration
    project: leubedane
    admins:
      - leubedane
    templateEngine: helm
    repoURL: https://github.com/leubedane/registration-deployment.git
  - name: table-tennis-tournament
    project: table-tennis-tournament
    path: namespaces
    noNamespaceCreation: true
    namespace: argocd
    templateEngine: helm
    repoURL: https://github.com/table-tennis-tournament/deployment-configuration.git
  - name: tekton-pipelines
  - name: argo 
  - name: openshift-logging
  - name: observability
  - name: kiali-operator
  - name: istio-operator
  - name: istio-system
