apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    password: AgBFXGUjRTP8OLjI2aG+D5Ujnh5t6Z/XUQtoqaZinxed7jlC4Spmux4rgOijVO0Pg4tnCA0yhu5eGGH8oK1ztagHH+pXrAH0P0bM51fX13OmLkwBsYaZzKli5EYYyeZR36PT3og4nT4okfCiOsgQLvXtthbBM/9hloi1upcAdDJ8KTTZykB+aQhnGxeprecY37mFLWWlt+I11lXrByB4k3AXoULDeCgvitGXG6hzI2yCX0lWL5AkHjpvFmyY0FtRIc+B+cbrEbmDBKeUl7hdkc4F3h5iUhY8mXWfka95WsmQtqGDru12sVMtqRX7VGC5OCggUL/xVjFmn9s7A7OOXAyFO3Ct4xYz32AO8egtcz+KhVfa7UT5P9ecnNkfXe59k/0TCx3ZiRGvERO0+Y6c9R35ib5qn6J8y9ghFSZGib8YYY15X7gWj9KouoKpqX1CHPQUUl7jkT3f4n10Cfvc3K+DAtWCoJMm7RhXYZy8kKwtpDTJDxFWXncB12F0xFc3ZhhPh9a5UE/bwNzPMnhzYfvgqRQkFantST7sYwJWDL5Lcdife1mNgTUoKI1f922sod6ujg7h9Kts/WOrv//KCxfTa7OVbcvRR68P0txqdQWOyqYO0V0NiWUgta8g0wR8YTQT4wgSh1WyhPLyZ5MKCYBuR20Tvi1jS86LyDkKYw1FoViLXeb5viwy3UsZSDxyxjAg
  template:
    metadata:
      creationTimestamp: null
      name: keycloak
      namespace: keycloak
status: {}

