apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: argo-ui
spec:
  host: argo.apps.baloise.dev
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: argo-ui
    weight: 100
status:
  ingress:
    - routerName: router